
# Domain Information
DomainDNSName: FYP.loc
DomainNetBIOSName: FYP
DomainPreferredLDAPServer: FYPDC.FYP.loc
DomainBaseDN: DC=fyp,DC=loc

# Service Account Information
ScannerUsername: svc_scanner
ScannerPassword: fakepassword123

WorkerUsername: svc_worker
WorkerPassword: fakepassword123

